# Generated by Django 3.1.4 on 2021-01-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20210123_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='subtotal',
            new_name='total',
        ),
    ]
